### ISSUE TITLE
about "Language-specific generic non-parallel data"

### ISSUE THREAD

**Issue by DwyaneLQY** [laihuiyuan/multilingual-tst#1]
Hi, Lai, I am a graduate student from sysu. I recently came across your published paper and found it to be extremely informative and insightful. Thank you for sharing it with the community.

While going through the paper, I had a question regarding "Language-specific generic non-parallel data". As I started exploring the News Crawl dataset, I noticed that there are multiple versions of the data available for each target language. Therefore, I would like to ask which version of the dataset should I choose?

Moreover, I noticed that you randomly selected 5 million sentences from News Crawl for fine-tuning. To reproduce your results, would it be possible for you to share with me the data of News Crawl that you used for fine-tuning? If so, I would greatly appreciate it. My email address is 243695664@qq.com.

Thank you for your time and consideration. I look forward to hearing from you soon.

**Comment by laihuiyuan** [comment]
Hi! Thanks for your interest in our work. I did not keep the data. To reproduce the results, you have to download all data (fr, it, pt) and select sentences containing 5 to 30 words as one version of the data is not enough.

**Comment by DwyaneLQY** [comment]
Thank you for your detailed answer!
Best wishes!
